### PR TITLE
Update 3-5-18-TrainingKeywordSpotting.ipynb

### PR DESCRIPTION
**Pull request by nebelgrau77**
Added necessary fixes for local use with TF2.x.

### CODE REVIEW

**Comment by plancherb1** [comment]
Did you delete this PR on purpose? (Closing a PR effectively deletes it)

**Comment by plancherb1** [comment]
If you want to contribute it to master you'll need to submit the PR and then leave it open and then I can merge it in. (Alternatively you may have found a bug in your own PR and deleted it for that reason and no worries if that is the case)

**Comment by plancherb1** [comment]
Nvm all those comments I see your new PR -- thank you for the help and Happy New Year!

**Comment by nebelgrau77** [comment]
Yeah, sorry for the confusion, I wasn't sure whether this was the right way to do it, and tried the same thing twice :)

**Pull request closed without merging**
