### PR TITLE
TF2 compatibility + alternative function return for batch testing

### PR DESCRIPTION
**Pull request by nebelgrau77**
added TF2 compatibility and an alternative function return for batch processing to 3-5-13-PretrainedModel

### CODE REVIEW

**Comment by plancherb1** [comment]
the ipynbs are causing a large amount of changes (which is wrong since I can see the few targeted changes you made) I think its just which cells are run and which outputs are shown. But/and to keep things simple I may manually do some of these. Let me take a look through later today in detail. Thank you!

**Comment by plancherb1** [comment]
Ok I think I manually did them -- I think in the future if you submit each different update as a separate PR that would be easier because some of them came with a very updated ipynb (which probably wasn't a big deal but scared me so I avoided it).

**Comment by nebelgrau77** [comment]
Sorry about that, but it happens kind of automatically: I actually did commit each notebook separately, but GH added them as new commits to the same PR. According to my current knowledge/skills, I can make a new PR on the same repo when you approve and close the previous one (there's probably a way to do it differently but I don't know, how :)

**Comment by plancherb1** [comment]
I think if you create a bunch of branches you can PR each of them individually but/and that feels like a huge pain to you so I will just try to move faster lol. Thanks again for all of the help/feedback! :)

**Pull request closed without merging**
